src/LaraCart.php
src/Traits/CouponTrait.php

@lukepolo requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/lukepolo/laracart/

Scrutinizer Auto-Fixes

---

src/LaraCart.php
tests/LaraCartTest.php

destroy cart now acutally destroys the session instance resolves #41

---

readme.md

changed getTotalDiscount -> totalDiscount

minor typo error

---

readme.md

finding a few random things as i use the package

minor updates to readme

---

readme.md

Was using attributes, noticed a few inconsistencies.

Update docs for Attributes

---

build/logs/clover.xml
readme.md
src/CartItem.php
src/LaraCart.php
tests/ItemsTest.php

Looks like this should merge in.

adding some basic search functionality (take 2)

---

composer.json
src/LaraCart.php
tests/ItemsTest.php

Hey dude!
With this PR, we'll be able to simply increment an item without having to add the entire item to an existing item. Tell me what u think ;)
Cheers!

Added increment/decrement feature

---

src/LaraCart.php

Updated increment/decrement with update method

---

readme.md

This one is linked with #83 & #84 ;)

Updated docs for increment/decrement feature

---

src/LaraCart.php
tests/FeesTest.php

Adding a way to remove all the fees in the cart. Fixed some doc blocks.

Remove all Fees in the Cart

---

src/CartItem.php

This needs to have a better fix, I believe 2.0 should solve some of this.

Allow for disabling auto updating sub items

---

src/CartFee.php

Add format parameter to getAmount() function to get the fee amount

Add format parameter to getAmount()

---

src/CartItem.php
src/LaraCart.php
tests/ItemsTest.php
tests/SubItemsTest.php

I sometimes need to get the price of an item / subtotal with tax included, I added flags to a couple of functions. Hopefully this is correct.

Added flags for return item prices with tax + added phpdoc

---

src/LaraCart.php

Add reflash before save session to keep old input in session

---

src/Coupons/Fixed.php

add format flag for displayValue()

add format flag for displayValue()

---

composer.json
src/Traits/CartOptionsMagicMethodsTrait.php
tests/MagicFunctionsTest.php

There are some cases where you need a tax bigger than 100%
And add a workaround for this: https://github.com/lukepolo/laracart/issues/170#issuecomment-298938912

Tax can be more than 100%

---

src/Traits/CartOptionsMagicMethodsTrait.php
tests/MagicFunctionsTest.php

Merge with #190

---

build/logs/clover.xml
src/CartItem.php

If you want to add subitems with quantity now it gets considered in the subtotal of the item
Lets say:
12" Pizza
- 2 Salami (as subitem)

Added ability for subitems to have quantity

---

build/logs/clover.xml
src/CartItem.php

Is it possible to merge #194 ? New version is missing this feature and causing problems after updating Laravel to 5.4 and therefore laracart to latest version

Fixed problem with tests (PR from 1.1)

---

src/LaraCart.php

Only delete if ```$this->cart->items``` has items in it... This will prevent an error being thrown when there are no items...

Only delete when there are items in cart

---

readme.md
src/LaraCart.php
tests/TotalsTest.php

This pull request applies code style fixes from an analysis carried out by [StyleJS](https://stylejs.io).
---
For more information, click [here](https://stylejs.io/analyses/1238).

Apply fixes from StyleJS

---

src/CartItem.php
src/CartSubItem.php
src/LaraCart.php
src/LaraCartServiceProvider.php
src/Traits/CartOptionsMagicMethodsTrait.php

Laravel 6 removed the str_ and arr_ helpers methods

Laravel 6 remove helpers + style fixes

---

.travis.yml
composer.json
phpunit.xml
src/Cart.php
src/CartFee.php
src/CartItem.php
src/CartSubItem.php
src/Contracts/LaraCartContract.php
src/Coupons/Fixed.php
src/LaraCart.php
src/config/laracart.php
tests/Coupons/Fixed.php
tests/LaraCartTest.php
tests/Models/TestItem.php

Solves #223 .
This is a breaking change. 
https://travis-ci.org/github/lukepolo/laracart/builds/681994350

Updating to use 7.4 and to use number formatter

---

src/Coupons/Fixed.php
src/Coupons/Percentage.php
src/LaraCart.php
tests/CouponsTest.php

pre tax discount fixes 

---

src/CartItem.php

fix copying object to use clone
